USE softblue;

INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (1, 'Alana da Silva Carvalho', 'alanadasilda@gmail.com', 'F');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (2,'ricardo mota filho', 'ricardo14@outlook.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (3,'jessica silva cavalcante', 'jeh_cavalcante@gmail.com', 'F');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (4,'pedro albuquerque werneck', 'wenerck01@gmail.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (5,'lyssandra gomes alves', 'lygomes@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (6,'marcos alves silva', 'silvamarcos1@gmail.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (7,'gilmar mendes santos', 'gilsantos@outlook.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (8,'eliana araujo carvalho', 'elicarvalho@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (9,'beatriz silva santos', 'beasilv4@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (10,'Vanessa alves', 'vanalves@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (11,'jennifer rosa muller', 'mullerjen@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (12,'davi mozer muller', 'davimuller54@gmail.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (13,'isabela silvino matos', 'isasilvin0@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (14,'iuri henzo mota', 'henzo50@gmailcom', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (15,'olavo lima pereira', 'olavolim4@gmail.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (16,'marly barbosa carvalho', 'barbosamarly@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (17,'isabela campos ferreira','isafer@gamil.com','m');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (18,'barbara gomes gaurson', 'baggomes@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (19,'carlos eduardo santos', 'cadusantos04@gmailcom', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (20,'samuel victor carvalho', 'samuelvic@gmail.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (21,'daniel victor santos', 'dansantos@gmailcom', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (22,'andressa galvao lima', 'dressgalvao@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (23,'flaviana vascon lima', 'vasconfla@outlook.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (24,'Pietro ravok santos', 'ravokpi@outlook.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (25,'abner pires correa', 'abner05@gmail.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (26,'lucas martines martins', 'martinsmartines@gmail.com', 'm');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (27,'Viviane costa correa', 'vivicorrea@gmail.com', 'f');
INSERT INTO aluno(cod_aluno, nome, email, sexo) VALUES (28,'haynoa pires gomes', 'haynoa01@gmail.com', 'f');