USE softblue;

INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (1, 'jailson sousa viana', 'são luís', 'maranhão','nordeste', '1');
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (2,'joao castelo', 'são luís', 'maranhao', 'nordeste', '2');
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (3,'santos dumont', 'sao luis','maranhao', 'nordeste', '3');
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (4, 'daniel de la touche', 'sao luis','maranhao', 'nordeste', 4);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (5, 'almeida junior', 'duque de caxias', 'rio de janeiro', 'sudeste', 5);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (6, 'josé sarney', 'sao luis', 'maranhao', 'nordeste', 6);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (7, 'jesus de praga', 'sao luis', 'maranhao', 'nordeste', 7);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (8, 'joaquim serra', 'sao luis', 'maranhao', 'nordeste', 8);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (9, 'joaquim serra', 'sao luis', 'maranhao', 'nordeste', 9);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (10, 'almeida junior', 'duque de caxias', 'rio de janeiro', 'sudeste',10);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (11, 'senador archer', 'codó', 'maranhao', 'nordeste', 11);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (12, 'jardim esperança','codó' ,'maranhao' , 'nordeste', 12);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (13, 'dezoito de novembro', 'são luis', 'maranhao', 'nordeste', 13);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (14, 'riscado mota', 'casimiro de abreu', 'rio de janeiro', 'sudeste',14);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (15, 'augusto lima', 'sao luis', 'maranhão', 'nordeste', 15);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (16, 'augusto lima', 'sao luis', 'maranhao', 'nordeste', 16);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (17, 'Afonso Pena', 'codó', 'maranhao','nordeste', 17);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (18, 'maximiano brandao', 'codó', 'maranhao', 'nordeste',18);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (19, 'marcio almeida', 'codó', 'maranhao','nordeste', 19);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (20, 'almeida bairros','codó', 'maranhao','nordeste', 20);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (21,'alameda chapadinha', 'codó', 'maranhão', 'nordeste', 21);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (22, 'geciano riscado mota','casimiro de abreu', 'rio de janeiro', 'sudeste',22);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (23,'rodolfo mota','casimiro de abreu', 'rio de janeiro', 'sudeste',23);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (24, 'santa helena','casimiro de abreu','rio de janeiro', 'sudeste', 24);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (25, 'mataruna','casimiro de abreu', 'rio de janeiro','sudeste',25);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (26, 'rio grande do sul','sao luis', 'maranhao', 'nordeste',26);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (27,'Dr dominice','são luis', 'maranhao','nordeste', 27);
INSERT INTO endereco(cod_endereco, rua, cidade, estado, regiao, cod_aluno) VALUES (28, 'Dr dominice','são luis', 'maranhao', 'nordeste',28);